"""tles and satellite_positions tables

Revision ID: 300744a9f11c
Revises: f2d82ec6da5a
Create Date: 2026-05-15 22:09:09.137789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300744a9f11c'
down_revision: Union[str, Sequence[str], None] = 'f2d82ec6da5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_positions',
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('alt_km', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('tle_epoch', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['norad_id'], ['satellites.norad_id'], name=op.f('fk_satellite_positions_norad_id_satellites')),
    sa.PrimaryKeyConstraint('norad_id', name=op.f('pk_satellite_positions'))
    )
    op.create_table('tles',
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('line1', sa.Text(), nullable=False),
    sa.Column('line2', sa.Text(), nullable=False),
    sa.Column('object_name', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='SPACETRACK', nullable=False),
    sa.ForeignKeyConstraint(['norad_id'], ['satellites.norad_id'], name=op.f('fk_tles_norad_id_satellites')),
    sa.PrimaryKeyConstraint('norad_id', name=op.f('pk_tles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tles')
    op.drop_table('satellite_positions')
    # ### end Alembic commands ###
