"""live space weather tables

Revision ID: 74bfa7f48a07
Revises: 768eb0bb052f
Create Date: 2026-05-15 21:27:20.151381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bfa7f48a07'
down_revision: Union[str, Sequence[str], None] = '768eb0bb052f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geomag_live',
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kp', sa.Float(), nullable=True),
    sa.Column('dst_estimate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('t', name=op.f('pk_geomag_live'))
    )
    op.create_table('proton_flux_live',
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('satellite', sa.String(length=16), nullable=False),
    sa.Column('flux_gt10', sa.Float(), nullable=True),
    sa.Column('flux_gt50', sa.Float(), nullable=True),
    sa.Column('flux_gt100', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('t', 'satellite', name=op.f('pk_proton_flux_live'))
    )
    op.create_table('solar_wind_live',
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bx_gsm', sa.Float(), nullable=True),
    sa.Column('by_gsm', sa.Float(), nullable=True),
    sa.Column('bz_gsm', sa.Float(), nullable=True),
    sa.Column('bt', sa.Float(), nullable=True),
    sa.Column('v', sa.Float(), nullable=True),
    sa.Column('n_p', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('p_dyn', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('t', name=op.f('pk_solar_wind_live'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_wind_live')
    op.drop_table('proton_flux_live')
    op.drop_table('geomag_live')
    # ### end Alembic commands ###
