"""satellites filter indexes

Revision ID: b178bf4157b8
Revises: ebf2e6574bb6
Create Date: 2026-05-13 21:44:03.402170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b178bf4157b8'
down_revision: Union[str, Sequence[str], None] = 'ebf2e6574bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_satellites_classification', 'satellites', ['classification'], unique=False)
    op.create_index('ix_satellites_regime', 'satellites', ['regime'], unique=False)
    op.create_index('ix_satellites_un_state', 'satellites', ['un_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_satellites_un_state', table_name='satellites')
    op.drop_index('ix_satellites_regime', table_name='satellites')
    op.drop_index('ix_satellites_classification', table_name='satellites')
    # ### end Alembic commands ###
