"""initial schema

Revision ID: d79c8f39d780
Revises: 
Create Date: 2026-05-13 21:05:29.941332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79c8f39d780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('norad_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('un_state', sa.String(length=64), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('mass_kg', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=8), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('constellation', sa.String(length=64), nullable=True),
    sa.Column('perigee_km', sa.Float(), nullable=True),
    sa.Column('apogee_km', sa.Float(), nullable=True),
    sa.Column('inclination_deg', sa.Float(), nullable=True),
    sa.Column('altitude_km', sa.Float(), nullable=True),
    sa.Column('elapsed_yrs', sa.Float(), nullable=True),
    sa.CheckConstraint("regime IN ('LEO', 'MEO', 'GEO', 'HEO')", name=op.f('ck_satellites_regime_valid')),
    sa.PrimaryKeyConstraint('norad_id', name=op.f('pk_satellites'))
    )
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(length=32), nullable=False),
    sa.Column('bootstrap_index', sa.Integer(), nullable=False),
    sa.Column('return_period_years', sa.Integer(), nullable=False),
    sa.Column('dst_min', sa.Float(), nullable=True),
    sa.Column('bz_min', sa.Float(), nullable=True),
    sa.Column('by_max', sa.Float(), nullable=True),
    sa.Column('v_max', sa.Float(), nullable=True),
    sa.Column('pdyn_max', sa.Float(), nullable=True),
    sa.Column('n_p_max', sa.Float(), nullable=True),
    sa.Column('kp_max', sa.Float(), nullable=True),
    sa.Column('j_gt10_peak', sa.Float(), nullable=True),
    sa.Column('j_gt30_peak', sa.Float(), nullable=True),
    sa.Column('j_gt100_peak', sa.Float(), nullable=True),
    sa.Column('fluence_gt10', sa.Float(), nullable=True),
    sa.Column('fluence_gt30', sa.Float(), nullable=True),
    sa.Column('fluence_gt100', sa.Float(), nullable=True),
    sa.Column('has_pfail', sa.Boolean(), nullable=False),
    sa.CheckConstraint('return_period_years IN (50, 100, 150)', name=op.f('ck_scenarios_return_period_valid')),
    sa.PrimaryKeyConstraint('scenario_id', name=op.f('pk_scenarios'))
    )
    op.create_table('vulnerability',
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=32), nullable=False),
    sa.Column('shield_mm', sa.Float(), nullable=True),
    sa.Column('tid_baseline_krad', sa.Float(), nullable=True),
    sa.Column('tid_sep_krad', sa.Float(), nullable=True),
    sa.Column('tid_total_krad', sa.Float(), nullable=True),
    sa.Column('p_fail', sa.Float(), nullable=False),
    sa.Column('classification_pfail', sa.String(length=16), nullable=False),
    sa.Column('f_access_gt10', sa.Float(), nullable=True),
    sa.Column('f_access_gt30', sa.Float(), nullable=True),
    sa.Column('f_access_gt100', sa.Float(), nullable=True),
    sa.Column('f_access_gt30_std', sa.Float(), nullable=True),
    sa.Column('rc_min', sa.Float(), nullable=True),
    sa.Column('rc_mean', sa.Float(), nullable=True),
    sa.Column('rc_max', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=True),
    sa.CheckConstraint("classification_pfail IN ('CRITICAL', 'ELEVATED', 'MODERATE', 'LOW', 'NEGLIGIBLE')", name=op.f('ck_vulnerability_classification_pfail_valid')),
    sa.CheckConstraint("source IN ('OTSO', 'ML')", name=op.f('ck_vulnerability_source_valid')),
    sa.ForeignKeyConstraint(['norad_id'], ['satellites.norad_id'], name=op.f('fk_vulnerability_norad_id_satellites')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], name=op.f('fk_vulnerability_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('norad_id', 'scenario_id', name=op.f('pk_vulnerability'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability')
    op.drop_table('scenarios')
    op.drop_table('satellites')
    # ### end Alembic commands ###
