"""live tables source defaults

Revision ID: f2d82ec6da5a
Revises: 74bfa7f48a07
Create Date: 2026-05-15 21:43:55.980626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d82ec6da5a'
down_revision: Union[str, Sequence[str], None] = '74bfa7f48a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proton_flux_live', sa.Column('source', sa.String(length=32), server_default='SWPC-GOES', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proton_flux_live', 'source')
    # ### end Alembic commands ###
